# Form implementation generated from reading ui file '.\UI_RAW\Items.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ItemsDialog(object):
    def setupUi(self, ItemsDialog):
        ItemsDialog.setObjectName("ItemsDialog")
        ItemsDialog.resize(241, 340)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=ItemsDialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 243, 341))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.MainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.MainLayout.setContentsMargins(0, 0, 0, 0)
        self.MainLayout.setObjectName("MainLayout")
        self.InputLayout = QtWidgets.QHBoxLayout()
        self.InputLayout.setObjectName("InputLayout")
        self.SelectionGrid = QtWidgets.QGridLayout()
        self.SelectionGrid.setObjectName("SelectionGrid")
        self.ItemText = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.ItemText.setObjectName("ItemText")
        self.SelectionGrid.addWidget(self.ItemText, 0, 2, 1, 1)
        self.ItemLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.ItemLabel.setObjectName("ItemLabel")
        self.SelectionGrid.addWidget(self.ItemLabel, 0, 0, 1, 1)
        self.PriceLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.PriceLabel.setObjectName("PriceLabel")
        self.SelectionGrid.addWidget(self.PriceLabel, 1, 0, 1, 1)
        self.PriceText = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.PriceText.setObjectName("PriceText")
        self.SelectionGrid.addWidget(self.PriceText, 1, 2, 1, 1)
        self.InputLayout.addLayout(self.SelectionGrid)
        self.MainLayout.addLayout(self.InputLayout)
        self.OutputLayout = QtWidgets.QVBoxLayout()
        self.OutputLayout.setObjectName("OutputLayout")
        self.ModificationLayout = QtWidgets.QHBoxLayout()
        self.ModificationLayout.setObjectName("ModificationLayout")
        self.AddButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.AddButton.setObjectName("AddButton")
        self.ModificationLayout.addWidget(self.AddButton)
        self.UpdateButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.UpdateButton.setObjectName("UpdateButton")
        self.ModificationLayout.addWidget(self.UpdateButton)
        self.DeleteButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.DeleteButton.setObjectName("DeleteButton")
        self.ModificationLayout.addWidget(self.DeleteButton)
        self.OutputLayout.addLayout(self.ModificationLayout)
        self.ResultLayout = QtWidgets.QHBoxLayout()
        self.ResultLayout.setObjectName("ResultLayout")
        self.OutputLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.OutputLabel.setObjectName("OutputLabel")
        self.ResultLayout.addWidget(self.OutputLabel)
        self.OutputText = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.OutputText.setReadOnly(True)
        self.OutputText.setObjectName("OutputText")
        self.ResultLayout.addWidget(self.OutputText)
        self.OutputLayout.addLayout(self.ResultLayout)
        self.MainLayout.addLayout(self.OutputLayout)
        self.ItemTable = QtWidgets.QTableView(parent=self.verticalLayoutWidget_3)
        self.ItemTable.setObjectName("ItemTable")
        self.MainLayout.addWidget(self.ItemTable)
        self.MainLayout.setStretch(0, 1)
        self.MainLayout.setStretch(2, 4)

        self.retranslateUi(ItemsDialog)
        QtCore.QMetaObject.connectSlotsByName(ItemsDialog)
        ItemsDialog.setTabOrder(self.ItemText, self.PriceText)
        ItemsDialog.setTabOrder(self.PriceText, self.AddButton)
        ItemsDialog.setTabOrder(self.AddButton, self.UpdateButton)
        ItemsDialog.setTabOrder(self.UpdateButton, self.DeleteButton)
        ItemsDialog.setTabOrder(self.DeleteButton, self.OutputText)
        ItemsDialog.setTabOrder(self.OutputText, self.ItemTable)

    def retranslateUi(self, ItemsDialog):
        _translate = QtCore.QCoreApplication.translate
        ItemsDialog.setWindowTitle(_translate("ItemsDialog", "Items"))
        self.ItemLabel.setText(_translate("ItemsDialog", "Item Name:"))
        self.PriceLabel.setText(_translate("ItemsDialog", "Item Price:"))
        self.AddButton.setText(_translate("ItemsDialog", "Add"))
        self.UpdateButton.setText(_translate("ItemsDialog", "Update"))
        self.DeleteButton.setText(_translate("ItemsDialog", "Delete"))
        self.OutputLabel.setText(_translate("ItemsDialog", "Result:"))
